import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, Check, ChevronRight, ClipboardCheck, FlaskConical, GitBranch, RefreshCw } from 'lucide-react';
import { request } from './api';
import type { Candidate, Role } from './types';
import { Badge, Modal, Spinner } from './App';

type Evaluation = {passed:boolean;regressions:number;improvements:number;total:number;limitations:string[];results:{name:string;expected_warning:boolean;before:boolean;after:boolean;regression:boolean;improvement:boolean}[]};
type Bundle = {id:string;title?:string;status:string;active:boolean;activated_at?:string;evaluation:Evaluation|null;limitations?:string[]};
const human=(value:unknown)=>String(value??'').replaceAll('_',' ');

export function AnalystView({role,token,act,busy,toast}:{role:Role;token:string;act:(fn:()=>Promise<void>)=>Promise<void>;busy:boolean;toast:(text:string)=>void}){
 const [candidates,setCandidates]=useState<Candidate[]>([]);
 const [bundles,setBundles]=useState<Bundle[]>([]);
 const [selected,setSelected]=useState<Candidate|null>(null);
 const [note,setNote]=useState('');
 const [status,setStatus]=useState('needs_evidence');
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState('');
 const [proposal,setProposal]=useState<Candidate|null>(null);
 const [patternId,setPatternId]=useState('');
 const [title,setTitle]=useState('');
 const [description,setDescription]=useState('');
 const [terms,setTerms]=useState('');
 const [nextAction,setNextAction]=useState('');
 const reload=useCallback(async()=>{setLoading(true);try{const [c,b]=await Promise.all([request<{candidates:Candidate[]}>('/v1/analyst/candidates',token),request<{bundles:Bundle[]}>('/v1/analyst/bundles',token)]);setCandidates(c.candidates);setBundles(b.bundles);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[token]);
 useEffect(()=>{void reload()},[reload]);
 const propose=(candidate:Candidate)=>{setSelected(null);setProposal(candidate);setPatternId('');setTitle('');setDescription('');setTerms('');setNextAction('');};
 return <>
  <div className="page-title"><div><div className="eyebrow">FROM REPORTS TO REVIEWED PATTERNS</div><h1>Look for what’s changing.</h1><p>Review contributed workflows and evaluate proposed patterns.</p></div><button className="button secondary" onClick={()=>void reload()} disabled={busy||loading}><RefreshCw size={16}/>Refresh</button></div>
  <div className="analyst-banner"><GitBranch size={22}/><p>Related tags create a review lead. They do not establish fraud, a shared campaign, or real-world emergence. Original case messages are excluded. A user may separately contribute a description of the workflow.</p><Badge>{role==='admin'?'Release admin':'Analyst'}</Badge></div>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="analyst-grid"><section><div className="section-heading"><h2>Candidate patterns</h2><Badge>{candidates.length} for review</Badge></div>
   {loading?<div className="loading-state"><Spinner/></div>:candidates.length?<div className="candidate-list">{candidates.map(c=><button key={c.id} className="panel candidate-card" onClick={()=>{setSelected(c);setNote('');setStatus('needs_evidence')}}><div><Badge tone={c.status==='candidate'?'blue':'neutral'}>{human(c.status)}</Badge><ChevronRight size={17}/></div><h3>{c.title||'Contributed workflow candidate'}</h3><p>{c.summary||'Review the contributed action categories and their limitations.'}</p><span>{c.report_count??1} report · Report independence unverified</span></button>)}</div>:<div className="panel empty-panel"><GitBranch size={28}/><h2>Evidence comes first.</h2><p>A separately consented report appears here after the user previews and shares a minimized report.</p></div>}
  </section><section><div className="section-heading"><h2>Detection versions</h2><Badge>{bundles.length} versions</Badge></div>
   {bundles.length?bundles.map(b=><article className="panel update-card" key={b.id}><div className="section-heading"><h3>{b.title||b.id}</h3><Badge tone={b.active?'green':'neutral'}>{b.active?'Active':human(b.status==='active'?'previously released':b.status)}</Badge></div><p className="field-help">{b.id==='baseline-v1'?'Original local rules baseline.':'Changes affect future assessments. Existing cases retain their recorded results until reassessed.'}</p>
    {b.evaluation&&<><div className="title-badges"><Badge tone={b.evaluation.passed?'green':'warning'}>{b.evaluation.passed?'Engineering checks passed':'Engineering checks failed'}</Badge><Badge>{b.evaluation.improvements} improvements · {b.evaluation.regressions} regressions</Badge></div><details className="evaluation-details"><summary>Inspect {b.evaluation.total} synthetic checks</summary><div className="evaluation-table-wrap"><table className="evaluation-table"><thead><tr><th>Fixture</th><th>Expected warning</th><th>Before</th><th>After</th></tr></thead><tbody>{b.evaluation.results.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.expected_warning?'Yes':'No'}</td><td>{r.before?'Warn':'No warning'}</td><td>{r.after?'Warn':'No warning'}</td></tr>)}</tbody></table></div></details>{b.evaluation.limitations.map((l,i)=><p className="field-help" key={i}>{l}</p>)}</>}
    <div className="button-row">{b.id!=='baseline-v1'&&!b.active&&<button className="button secondary small" disabled={busy} onClick={()=>void act(async()=>{await request(`/v1/analyst/updates/${b.id}/evaluate`,token,'POST',{});await reload();toast('Evaluation completed. Inspect the checks and limitations.');})}><FlaskConical size={14}/>Evaluate</button>}
    {role==='admin'&&!b.active&&((b.evaluation?.passed)||b.id==='baseline-v1')&&<>{b.id!=='baseline-v1'&&<button className="button primary small" disabled={busy} onClick={()=>void act(async()=>{await request(`/v1/admin/bundles/${b.id}/activate`,token,'POST',{});await reload();toast('Detection version activated for future assessments.');})}><Check size={14}/>Activate</button>}{(b.activated_at||b.id==='baseline-v1')&&<button className="text-button" disabled={busy} onClick={()=>void act(async()=>{await request(`/v1/admin/bundles/${b.id}/rollback`,token,'POST',{});await reload();toast('Detection version restored.');})}>Restore this version</button>}</>}
    </div></article>):<div className="panel empty-updates"><ClipboardCheck size={29}/><h3>No versions available</h3><p>Refresh after connecting to the service.</p></div>}
  </section></div>
  {selected&&<Modal title="Review the candidate" onClose={()=>setSelected(null)} wide><div className="title-badges"><Badge>{human(selected.status)}</Badge><Badge>{selected.workflow_narrative?'User-described workflow':'Action categories only'}</Badge></div><h3>{selected.title||'Workflow candidate'}</h3>{typeof selected.workflow_narrative==='string'&&selected.workflow_narrative&&<section className="candidate-narrative"><h4>Contributed workflow</h4><p>{selected.workflow_narrative}</p><span className="field-help">User-supplied description. Source accuracy and report independence are unverified.</span></section>}{Array.isArray(selected.similar_candidates)&&selected.similar_candidates.length>0&&<section className="candidate-narrative"><h4>Related review leads</h4>{(selected.similar_candidates as {id:string;shared_tags?:string[];method?:string}[]).map(match=><div className="related-candidate" key={match.id}><button className="text-button" onClick={()=>{const other=candidates.find(c=>c.id===match.id);if(other){setSelected(other);setNote('');setStatus('needs_evidence')}}}>{candidates.find(c=>c.id===match.id)?.title||match.id} <ArrowRight size={13}/></button><p>{match.shared_tags?.map(human).join(', ')||'Similarity requires review'}</p><span className="field-help">{human(match.method)}; does not establish a common campaign.</span></div>)}</section>}<details className="evaluation-details"><summary>Inspect the full contributed evidence</summary><pre className="json-preview review-data">{JSON.stringify(selected,null,2)}</pre></details><form onSubmit={e=>{e.preventDefault();void act(async()=>{const candidate=await request<Candidate>(`/v1/analyst/candidates/${selected.id}/reviews`,token,'POST',{status,reason:note.trim()});await reload();setSelected(candidate);setNote('');toast('Review decision recorded. No detection update has been released.');})}}><label>Review decision<select value={status} onChange={e=>setStatus(e.target.value)}><option value="needs_evidence">Needs more evidence</option><option value="existing_pattern">Existing pattern</option><option value="rejected">Reject candidate</option><option value="accepted_for_evaluation">Accept for evaluation</option></select></label><label>Review reasoning<textarea rows={3} required minLength={5} value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder="State what is supported, what is uncertain, and what needs independent verification."/></label><div className="modal-actions">{selected.status==='accepted_for_evaluation'&&<button type="button" className="button secondary" onClick={()=>propose(selected)}>Draft a pattern <ArrowRight size={15}/></button>}<button className="button primary" disabled={busy||note.trim().length<5}>{busy?<Spinner/>:<Check size={16}/>}Save review</button></div></form></Modal>}
  {proposal&&<Modal title="Propose a detection update" onClose={()=>setProposal(null)} wide><p className="modal-description">A reviewed candidate provides a lead. Your literal pattern still needs engineering checks, independent validation, and a release decision.</p><form onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/v1/analyst/updates',token,'POST',{candidate_id:proposal.id,title:title.trim(),pattern:{id:patternId.trim(),description:description.trim(),term_groups:terms.split('\n').map(line=>line.split('|').map(term=>term.trim()).filter(Boolean)).filter(group=>group.length),next_action:nextAction.trim()}});setProposal(null);await reload();toast('Pattern proposed. Evaluate it before a release administrator can activate it.');})}}><div className="two-fields"><label>Version title<input required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Release deposit review"/></label><label>Unique pattern identifier<input required pattern="[a-z][a-z0-9_]{2,50}" maxLength={51} value={patternId} onChange={e=>setPatternId(e.target.value)} placeholder="e.g. release_deposit"/></label></div><label>Concern shown to the user<textarea required minLength={10} maxLength={300} rows={2} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the request and why it deserves verification."/></label><label>Required phrase groups<textarea required rows={4} maxLength={3200} value={terms} onChange={e=>setTerms(e.target.value)} placeholder={'release code | release token\nprocessing deposit | clearance deposit'}/></label><p className="field-help">One required group per line (up to five). Separate alternatives with |. Every group must match. Use 1–8 literal phrases per group, 3–80 characters each.</p><label>Suggested next step<textarea required minLength={10} maxLength={500} rows={3} value={nextAction} onChange={e=>setNextAction(e.target.value)} placeholder="Give one specific, proportionate verification step."/></label><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setProposal(null)}>Cancel</button><button className="button primary" disabled={busy}>{busy?<Spinner/>:<GitBranch size={16}/>}Create proposal</button></div></form></Modal>}
 </>;
}
